title: Simran Pathak # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Adaptable data analyst adept in data collection, interpretation, and analysis in a fast-paced workplace. Excellent grasp and skill in data analysis tools such as 
  SQL, Excel, Tableau, and Python, Strong communication, organizational and analytical skills.  
    <br><br>
  <a href="https://www.linkedin.com/in/simran-pathak">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
